server:
  port: 8084
spring:
  application:
    name: config-server
  profiles:
    active: @activatedProperties@
  jackson:
    serialization:
      write-dates-as-timestamps: true
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhouchao4664/spring-cloud-config-server-test.git
          username: zhouchao19890214@163.com
          password: zhouchao19890214
#        native:
#          add-label-locations: true
#          search-locations: C:\Users\RAYDATA\AppData\Local\Temp\config-repo-5937633445309018274\

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:123456@localhost:8080/eureka
  instance:
    prefer-ip-address: true

