server:
  port: 8082

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:123456@localhost:8080/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
        - id: test
          uri: lb://service-order
          predicates:
            - Path=/order/**
#            - Auth=Authorization,token
#

