spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring-test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      percentage: 1.0
#log
logging:
  level:
    org.springframework.web: trace
    org.springframework.actuator: trace
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.http.web.reactive: debug
    reactor.ipc.netty: debug