server:
  port: 8083
  servlet:
    context-path: /user
spring:
  application:
    name: service-user
  profiles:
    active: @activatedProperties@
  jackson:
    serialization:
      write-dates-as-timestamps: true

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    #feign调用默认是1000毫秒=1秒
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000
      circuitBreaker:
        sleepWindowInMilliseconds: 5000
        forceClosed: true
    OrderFeignClient#orderListByUser():
      execution:
        isolation:
          strategy: THREAD
          semaphore:
            maxConcurrentRequests: 10
  threadpool:
    default:
      coreSize: 20 #并发执行的最大线程数，默认10
      maxQueueSize: 1000 #BlockingQueue的最大队列数，默认值-1
      queueSizeRejectionThreshold: 800 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝，默认值5
ribbon:
  #请求处理的超时时间
  ReadTimeout: 5000
  SocketTimeout: 5000
  #请求连接的超时时间
  ConnectTimeout: 5000